# Development Profile Configuration
spring.application.name=Neurozen Platform

# Server Configuration
server.port=8081

# Spring DataSource Configuration - PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/iannawrocki
spring.datasource.username=iannawrocki
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.neurozen.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Spring Boot DevTools - Auto browser launch
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
